//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nbcc
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_contact
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string subjects { get; set; }
        public string msg { get; set; }
    }
}
